### PR TITLE
Experimental Svelte 5 Support

### PR DESCRIPTION
**Pull request by tsar-boomba**
# Updates some dependencies:
- Storybook
- estree
- svelte
- vite
- vitest

# Issues
1. Collect stories test cannot pass even though the addon works fine in actual storybook
2. Args to components cannot be inferred when using runes mdoe in a component. For example, in the ArgsTable story, you cannot tweak any of the props from the story ui.

### CODE REVIEW

**Comment by xeho91** [comment]
Hi, this is just a heads up.

I've had a time to do some research with Storybook support for Svelte 5, including this addon.

While testing your PR, I've noticed that the stories in the group `MetaExport` doesn't work at runtime.

**Comment by xeho91** [comment]
There's my attempt: 
https://github.com/tsar-boomba/addon-svelte-csf/pull/1

Feel free to cherry-pick, and let me know if I can help more with testing/contributing.

**Comment by JReinhold** [comment]
@xeho91 could you open a PR directly to this repo, so that we're not all blocked by each other?

Feel free to attribute relevant changes to @tsar-boomba

**Comment by tsar-boomba** [comment]
Closing in favor of #178

**Pull request closed without merging**
