### PR TITLE
Add ESM support

### PR DESCRIPTION
**Pull request by TheComputerM**
Followed https://github.com/storybookjs/addon-kit/pull/11/files

### CODE REVIEW

**Comment by shilman** [comment]
@TheComputerM can you resolve conflicts on these files?

**Comment by shilman** [comment]
@TheComputerM thanks for updating. i get the following error when testing. can you please look into it?

```
$ yarn storybook
ERR! Error: Cannot find module './dist/esm/preset/preview'
...
```

**Comment by TheComputerM** [comment]
Yeah, looking into it, do you think updating from storybook 6.1 to 6.2 could be causing it?

**Comment by TheComputerM** [comment]
@shilman Fixed the code, shall I also update storybook to 6.2.9 from 6.2.1?

**Comment by TheComputerM** [comment]
Thank you very much @shilman ! Please @ me if there are any issues.

**Review by shilman — COMMENTED** [review]
LGTM!

**Pull request merged**
