### PR TITLE
Update dependencies to support svelte@4

### LINKED ISSUE #109: [Feature Request] Support of Svelte 4
### Describe the feature

Is there a plan to support Svelte 4? I would be happy to help with this if possible.
Storybook has an alpha release in the oven where it will support Svelte v4: https://github.com/storybookjs/storybook/pull/23197

### Additional context
https://svelte.dev/blog/svelte-4

### PR DESCRIPTION
**Pull request by RSWilli**
Closes #109

* Updated the types according to https://github.com/sveltejs/svelte/pull/8512
* Updated the storybook dependencies to support svelte 4, see https://github.com/storybookjs/storybook/releases/tag/v7.0.27
* Use svelte 4 internally, but allow svelte 3 as peer dependency
* use Node 20 in the build pipeline
* I had to remove the webpackFinal stuff in the storybook main.js for it to work and according to [this comment](https://github.com/storybookjs/addon-svelte-csf/issues/109#issuecomment-1623274565) it was not needed either

The included storybook run fine for me locally.

I am not familiar with the build process with github actions, so feel free to edit anything.

### CODE REVIEW

**Comment by RSWilli** [comment]
I do not know if the peer dependency version of storybook should also be `^7.0.27`, or if it will be fine this way

**Review by JReinhold — APPROVED** [review]
This is great, thank you for this! 💪

**Comment by shilman** [comment]
:rocket: PR was released in [`v3.0.4`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v3.0.4) :rocket:

**Comment by oscard0m** [comment]
Thanks for the great job and for the time invested in this @RSWilli ! 👏🏽 

---

Is it possible this should be using `@storybook/*@7.1.0`? I see some extra commits supporting Svelte 4 done in that release:
- https://github.com/storybookjs/storybook/releases/tag/v7.1.0-rc.2

---

Also, when running my project with `v3.0.4` I get the following error which I'm not sure if it's related:

<details><summary>stacktrace</summary>
<p>

```
Failed to load preset: {"type":"presets","name":"/Users/XXX/dev/mainmatter/chouchou/node_modules/.pnpm/@storybook+addon-svelte-csf@3.0.4_@storybook+svelte@7.1.0_@storybook+theming@7.0.22_@sveltejs_h2rr5co6q2uverg6qodhdmucde/node_modules/@storybook/addon-svelte-csf/preset.js"} on level 1
ERR! /Users/XXX/dev/mainmatter/chouchou/node_modules/.pnpm/@storybook+addon-svelte-csf@3.0.4_@storybook+svelte@7.1.0_@storybook+theming@7.0.22_@sveltejs_h2rr5co6q2uverg6qodhdmucde/node_modules/@storybook/addon-svelte-csf/dist/cjs/preset/index.js:1
ERR! import { svelteIndexer } from './indexer.js';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at internalCompileFunction (node:internal/vm:73:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1220:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
ERR!     at Object.newLoader (/Users/XXX/dev/mainmatter/chouchou/node_modules/.pnpm/esbuild-register@3.4.2_esbuild@0.18.11/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at extensions..js (/Users/XXX/dev/mainmatter/chouchou/node_modules/.pnpm/esbuild-register@3.4.2_esbuild@0.18.11/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
ERR!     at Module._load (node:internal/modules/cjs/loader:960:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
ERR!     at require (node:internal/modules/cjs/helpers:110:18)
ERR!  /Users/XXX/dev/mainmatter/chouchou/node_modules/.pnpm/@storybook+addon-svelte-csf@3.0.4_@storybook+svelte@7.1.0_@storybook+theming@7.0.22_@sveltejs_h2rr5co6q2uverg6qodhdmucde/node_modules/@storybook/addon-svelte-csf/dist/cjs/preset/index.js:1
ERR! import { svelteIndexer } from './indexer.js';
ERR! ^^^^^^
ERR!
ERR! SyntaxError: Cannot use import statement outside a module
ERR!     at internalCompileFunction (node:internal/vm:73:18)
ERR!     at wrapSafe (node:internal/modules/cjs/loader:1178:20)
ERR!     at Module._compile (node:internal/modules/cjs/loader:1220:27)
ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
ERR!     at Object.newLoader (/Users/XXX/dev/mainmatter/chouchou/node_modules/.pnpm/esbuild-register@3.4.2_esbuild@0.18.11/node_modules/esbuild-register/dist/node.js:2262:9)
ERR!     at extensions..js (/Users/XXX/dev/mainmatter/chouchou/node_modules/.pnpm/esbuild-register@3.4.2_esbuild@0.18.11/node_modules/esbuild-register/dist/node.js:4807:24)
ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
ERR!     at Module._load (node:internal/modules/cjs/loader:960:12)
ERR!     at Module.require (node:internal/modules/cjs/loader:1143:19)
ERR!     at require (node:internal/modules/cjs/helpers:110:18)
```

</p>
</details> 

<details><summary>This is my list of dependencies</summary>
<p>

```json
"devDependencies": {
   "@fontsource-variable/inter": "^5.0.3",
   "@playwright/test": "1.36.1",
   "@storybook/addon-essentials": "^7.1.0",
   "@storybook/addon-interactions": "^7.1.0",
   "@storybook/addon-links": "^7.1.0",
   "@storybook/addon-styling": "^1.3.4",
   "@storybook/addon-svelte-csf": "^3.0.4",
   "@storybook/blocks": "^7.1.0",
   "@storybook/jest": "^0.1.0",
   "@storybook/svelte": "^7.1.0",
   "@storybook/sveltekit": "^7.1.0",
   "@storybook/test-runner": "^0.11.0",
   "@storybook/testing-library": "^0.2.0",
   "@sveltejs/adapter-cloudflare": "^2.3.1",
   "@sveltejs/kit": "1.22.3",
   "@tailwindcss/forms": "^0.5.3",
   "@tailwindcss/typography": "^0.5.9",
   "@types/testing-library__jest-dom": "^5.14.8",
   "@typescript-eslint/eslint-plugin": "5.62.0",
   "@typescript-eslint/parser": "5.62.0",
   "autoprefixer": "10.4.14",
   "chromatic": "^6.19.8",
   "concurrently": "^8.2.0",
   "eslint": "8.45.0",
   "eslint-config-prettier": "8.8.0",
   "eslint-plugin-playwright": "^0.15.1",
   "eslint-plugin-promise": "^6.1.1",
   "eslint-plugin-storybook": "^0.6.12",
   "eslint-plugin-svelte": "2.32.2",
   "postcss": "8.4.26",
   "postcss-import": "^15.1.0",
   "postcss-load-config": "4.0.1",
   "prettier": "2.8.8",
   "prettier-plugin-jsdoc": "^0.4.2",
   "prettier-plugin-svelte": "2.10.1",
   "prettier-plugin-tailwindcss": "^0.4.0",
   "react": "^18.2.0",
   "react-dom": "^18.2.0",
   "storybook": "^7.1.0",
   "svelte": "4.0.5",
   "svelte-check": "3.4.6",
   "tailwindcss": "3.3.3",
   "tslib": "2.6.0",
   "typescript": "5.1.6",
   "vite": "4.4.4",
   "vitest": "0.33.0"
},
```

</p>
</details>

Let me know if this relates to this issue or if I need to open a new one with more information.

Again, thanks for the effort and giving back to the community ❤️

**Comment by RSWilli** [comment]
@oscard0m I am getting the same error here, I think this happens because the types are now svelte 4 typings, which are incompatible with the svelte 3 typings in my project

I think this needs a new PR, if we want to support both svelte 3 and 4

**Comment by oscard0m** [comment]
> @oscard0m I am getting the same error here, I think this happens because the types are now svelte 4 typings, which are incompatible with the svelte 3 typings in my project

Thanks for the quick answer and for giving some light here @RSWilli!

> I think this needs a new PR, if we want to support both svelte 3 and 4

I'm not sure what are the steps to follow:
- Do we want `addon-svelte-csf` to be retro-compatible with Svelte 3? In my mind, this should be a major release, and users can stay with in the previous version, which supports Svelte v3
- Do you know What is the versioning criteria for this addon? @JReinhold

**Comment by JReinhold** [comment]
I think @joelmukuthu is correct, that what you're seeing @oscard0m is #111.

> I think this happens because the types are now svelte 4 typings, which are incompatible with the svelte 3 typings in my project

@RSWilli I don't think the typings should be breaking, because we did the same changes in core without breaking anything. But if they indeed are, then we should revert this PR and release it as a major instead.

**Comment by JReinhold** [comment]
@benpaquier the error you're seeing is #111, which comes from Storybook v7.1. I suggest you try pinning your Storybook dependencies to version [`7.0.27`](https://github.com/storybookjs/storybook/releases/tag/v7.0.27).

#113 should fix this when it's released.

**Pull request merged**
