### PR TITLE
feat: Support for preprocessors in .stories.svelte

### LINKED ISSUE #4: TypeScript and Preprocessors support
### Describe the bug

Trying to use TypeScript in the stories.svelte caused error: `ParseError: Unexpected token`

``` 
<script lang="ts">
  import type { IRoute } from './IRoute';

  const ROUTES: IRoute[] = [
    {
      url: '/',
      title: 'Home',
    },
   ...
  ]

</script>
```

### Expected behavior

TypeScript should work using svelte preprocessor: https://svelte.dev/docs#svelte_preprocess

### Screenshots and/or logs

```
WARNING in ./src/modules/presentational/components/nav-bar2/NavBar2.stories.svelte
Module build failed (from ./node_modules/@storybook/addon-svelte-csf/dist/parser/svelte-stories-loader.js):
ParseError: Unexpected token
    at error (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16752:20)
    at Parser$1.error (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16828:10)
    at Parser$1.acorn_error (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16822:15)
    at Object.read_script [as read] (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:7501:17)
    at tag (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:15887:34)
    at new Parser$1 (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16787:22)
    at parse$3 (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:16919:21)
    at Object.compile (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/svelte/compiler.js:29918:18)
    at extractStories (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/@storybook/addon-svelte-csf/dist/parser/extract-stories.js:49:32)
    at Object.transformSvelteStories (/Users/pli/my/git/engineforce/super-core/clients/boson/node_modules/@storybook/addon-svelte-csf/dist/parser/svelte-stories-loader.js:64:52)
 @ \.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|svelte))$ (./src sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|jsx|ts|tsx|svelte))$) ./modules/presentational/components/nav-bar2/NavBar2.stories.svelte
 @ ./.storybook/generated-stories-entry.js
```

### Environment

 - OS: MacOS Catalina 10.15.7
 - Node.js version: v12.13.1
 - NPM version: 6.12.1
 - svelte@3.35.0
 - @storybook/svelte@6.1.21
 - @storybook/addon-svelte-csf@1.0.0

### PR DESCRIPTION
**Pull request by bfanger**
Fixes #4

Uses the preprocess settings from the **svelteOptions** defined in `.storybook/main.js` 
The same preprocess settings that are used for regular .svelte files are now also applied to the *.stories.svelte files

### CODE REVIEW

**Comment by benbender** [comment]
ping @shilman? :)

**Comment by bfanger** [comment]
Correct, the extracting of stories would fail as no prepossessing was applied 

As you mentioned sveltekit, i'd recommend using the [storybook-builder-vite](https://github.com/storybookjs/builder-vite) (which already works with typescript inside .stories.svelte files)

**Comment by j3rem1e** [comment]
This will break jest tests. That's why I didn't implements this request.

You should probably implements a sync version if not preprocessor are set. 
And provide an async jest transformer for jest >= 27

**Comment by j3rem1e** [comment]
You should probably too add an ts example.

**Comment by bfanger** [comment]
```
Test Suites: 10 passed, 10 total
Tests:       43 passed, 43 total
Snapshots:   48 passed, 48 total
Time:        5.574 s
Ran all test suites.
```
No test were broken, or are there additional tests i'm not aware of?

The unittest don't interact with the now async functions, and although the external api has changed, it still conforms to the webpack loader api specification.

**Comment by j3rem1e** [comment]
That's because you didn't add a ts stories.svelte

You add to apply the same svelteOptions to the file jest-transform in order to test ts stories.

**Comment by benbender** [comment]
From my testing it seems to work fine on builder-vite and breaks on webpack4/5 :/

**Comment by bfanger** [comment]
I've added unittest and tweaked jest to allow running async tests.

**Comment by j3rem1e** [comment]
> I've added unittest and tweaked jest to allow running async tests.

I don't see any change on jest-transform ? ^^

**Comment by bfanger** [comment]
Jest already had a babel transform, i've enabled 
"@babel/plugin-transform-runtime" for test to enable async unittests

**Comment by j3rem1e** [comment]
I'm sorry to insist, but I don't know how it can work.

jest-transform is the transformation which allow to use storyshots with this addon. It compiles svelte native stories into tests which can then be consumed with storyshots. Internally, it compiles svelte files here : https://github.com/storybookjs/addon-svelte-csf/blob/main/src/jest-transform.js#L6

If you don't add here preprocessor supports, I don't see how it process ts stories.

to test it, you should create a ts story and a new snapshots should be generated for this story.

**Comment by bfanger** [comment]
Please upgrade your project to Jest 27, then we'll be able to update the jest-transform.js to an [AsyncTransformer](https://jestjs.io/docs/code-transformation#writing-custom-transformers):

```js
const svelte = require('svelte/compiler');

const parser = require.resolve('./parser/collect-stories').replace(/[/\\]/g, '/');

async function processAsync(src, filename, options) {
  console.log('processAsync called for ', filename);
  if (options.preprocess) {
    src = await svelte.preprocess(options.preprocess,{ filename });
  }
  const result = svelte.compile(src, {
    format: 'cjs',
    filename,
    dev: true,
  });

  const code = result.js ? result.js.code : result.code;

  const z = {
    code: `${code}
    const { default: parser } = require('${parser}');
    const md = parser(module.exports.default, {});
    module.exports = { default: md.meta, ...md.stories };
    Object.defineProperty(exports, "__esModule", { value: true });`,
    map: result.js ? result.js.map : result.map,
  };
  return z;
}

exports.processAsync = processAsync;
```

Jest 26 doesn't support asynchronous [transformers](https://jestjs.io/docs/26.x/tutorial-react#custom-transformers).

**Comment by benmccann** [comment]
We should read the preprocess options from `svelte.config.js`. See https://github.com/storybookjs/builder-vite/pull/428

**Comment by AcePetrucci** [comment]
Any updates on this PR? I'm avoiding using `addon-svelte-csf` while it doesn't properly support TS :/

**Comment by bfanger** [comment]
I've rebased the changes, the PR still works and adds Typescript support to the addon, but it breaks a workflow used by the maintainer.

I can't fix that until this project upgrades to  Jest 27

( Until then I'd recommend switching to a Vite based Storybook setup, which does have Typescript support )

**Comment by IanVS** [comment]
@bfanger if I understand correctly (I may not be), I think the concern is for consuming projects that are using jest 26 or previous, along with storyshots and this addon.  I'm not sure how updating a dev dependency of this project would solve that problem.  

Perhaps a compromise would be adding a disclaimer that TS stories will not work with storyshots?  Not everybody uses storyshots, and this PR would give value to those who are not using it, while I think the situation does not change for those who do, right?

**Comment by IanVS** [comment]
FWIW, here's a PR to upgrade jest in this repo: https://github.com/storybookjs/addon-svelte-csf/pull/71

**Comment by IanVS** [comment]
@j3rem1e I think you had some ideas previously of reading the svelte config in a single place and then providing it to addons and the vite builder.  Do you recall what you had in mind for that?

**Comment by bfanger** [comment]
Storyshots run succesfully:
jest svelteshots success

In `src/jest-transform.js` i've  changed `function process` to `async function processAsync`  and added:

```js
if (options.preprocess) {
    src = await svelte.preprocess(options.preprocess,{ filename });
}
```

But adding a `lang="ts"` to a `<script>` will result in `Invalid synchronous transformer module` errors form Jest :-(
Also when running `yarn test --no-cache sveltehots` results in **No tests found**

**Comment by bfanger** [comment]
@IanVS maybe https://github.com/svelteness/svelte-jester/blob/master/src/svelteconfig.js can be used as inspiration for loading the config

**Comment by IanVS** [comment]
@bfanger we can use svelte itself to load the config, see https://github.com/storybookjs/builder-vite/pull/428/files#diff-1897e37c00f0a892e59db90901f310d352427ba2bd39472789bbd91a1e48c8efR5 from builder-vite.

The issue is that it's kind of a bummer to have to load it in the builder, in this addon, etc, over and over.  It would be kind of cool to load it once (maybe in the svelte renderer?) and have a way to expose it to the builder, addons, etc.

**Comment by JReinhold** [comment]
This PR has gone stale, as the `main` branch have seen significant changes since. I'm not quite sure if it's relevant anymore, I think this feature is now fully supported anyway - at least in Vite-based projects.

If there is still a need for this, feel free to open a new PR.

**Pull request closed without merging**
