### PR TITLE
Implement a Svelte StoryIndexer

### LINKED ISSUE #65: Add indexer support
Currently `stories.svelte` files are incompatible with:
- story index generation https://github.com/storybookjs/storybook/issues/18081
- storybook test runner https://github.com/storybookjs/test-runner/issues/80

To address this, we've added an "indexer" API to Storybook core for 7.0: https://github.com/storybookjs/storybook/pull/18355

If `addon-svelte-csf` were to implement an indexer, it would solve the above problems, plus other future problems as we build more on top of the story index (which we will definitely do more of in core)

### PR DESCRIPTION
**Pull request by j3rem1e**
Upgrade to Storybook v7 (alpha) and webpack5
Implement a new StoryIndexer in order to use the new "stories.json" format.

Fix #65 

Two bugs, but I am not sure it come from this implementation : 
- Story background is not defined, it must be set by hand in the toolbar (probably a regression from alpha 29, or an error in the upgrade of the dependencies ?)
- Some stories are not rendered in the Doc panel (and some are..). I didn't check in the official svelte kitchen sink if it come from the alpha29

<details>
  <summary>📦 Published PR as canary version: <code>2.0.9--canary.69.9b95d2b.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install @storybook/addon-svelte-csf@2.0.9--canary.69.9b95d2b.0
  # or 
  yarn add @storybook/addon-svelte-csf@2.0.9--canary.69.9b95d2b.0
  ```
</details>

### CODE REVIEW

**Comment by IanVS** [comment]
@j3rem1e what's the best way for us to test this out?  Would you be willing to release it in an alpha version, so that we can experiment with it with recent 7.0 alphas and with the svelte-vite framework?

**Comment by j3rem1e** [comment]
It has been published with version "2.0.8--canary.8172dc5.0". We can maybe create a "future" branch, or merge it on the current branch (it should work if I remove TS definition, which doesn't exists on main)

**Comment by IanVS** [comment]
cool, I'll try out the canary, I didn't see that, thanks.

**Comment by gbkwiatt** [comment]
Is there any progress on that ? It seems to work , but now there is newer canaries versions of 2.0.9 that can't be really tested without this indexer fix

**Review by JReinhold — APPROVED** [review]
I just tested it out with `v7.0.0-alpha.41` and everything seems to work perfectly.
I took the liberty to push a few fixes.

LGTM! 💪

**Comment by shilman** [comment]
:rocket: PR was released in [`v2.0.9`](https://github.com/storybookjs/addon-svelte-csf/releases/tag/v2.0.9) :rocket:

**Comment by j3rem1e** [comment]
You have merged an upgrade to v7.0.0-alpha in a minor version ?
this will break any projects using this addon, or I am wrong ?

**Comment by JReinhold** [comment]
sorry, this was a complete blunder from me.

you are both right. I'll try to fix it.

**Comment by IanVS** [comment]
Thanks for the catch, @j3rem1e, and thanks for the fixup, @JReinhold!

**Pull request merged**
